### PR TITLE
Add animated banner.

### PR DESCRIPTION
**Pull request by PabloMK7**
(This is my fisrt pull request, I hope I did this right :S)

Added an animated banner, you can see it in action [here.](http://gbatemp.net/threads/homebrew-launcher-loader-ntr-cfw-banners.439596/)

### CODE REVIEW

**Comment by yellows8** [comment]
"sdk tools" Missed that earlier...

**Comment by mariohackandglitch** [comment]
What do you mean with sdk tools?

**Comment by yellows8** [comment]
https://gbatemp.net/threads/homebrew-launcher-loader-ntr-cfw-banners.439596/#post-6636619

**Comment by mariohackandglitch** [comment]
I mean, what is the problem of that? Afaik, the current banner model is based on the sdk dummy banner, but with changed texture.

**Comment by yellows8** [comment]
" sdk dummy banner" Eh?

**Comment by mariohackandglitch** [comment]
Yep, there is a "default" banner on the sdk, if you compare it with a banner generated with bannertool, you'll see the texture and music are the only difference.

Anyway, if you don't like the banner because it was made with SDK, then it's your choice and I'm not gonna question it :P

**Comment by yellows8** [comment]
Wasn't aware of that, always assumed it was based on an official app's banner.

**Comment by mariohackandglitch** [comment]
Found a screenshot of it. http://m.imgur.com/x6ocboI

**Pull request closed without merging**
